Fix tests
GENIVI/vehicle_signal_manager pull request #47
Opened 2018-05-01 16:11 UTC by gctucker

This is to fix various issues with the unit tests and make it possible to extend them with new IPC modules.

* Fix false positive failures with the `ZeromqIPC` due to arbitrary sleep; wait for the VSM process to end instead
* Separate `ZeromqIPC` related code to a new class and run the same test cases with both `ZeromqIPC` and `DebugIPC`

2018-05-02 10:58 UTC, kov requested changes
I'm not a big fan of mixins, have you considered putting the tests on a base class? They could be in TestVSM, since it is the base class for the ZeroMQ class, or it can be a separate one that inherits from unittest.TestCase and gets inherited by TestVSM?

2018-05-03 07:10 UTC, gctucker commented
The issue is that to test the case when an IPC module returns `None` (see #44) I need to run a test case with a test IPC class and not with the regular IPC modules (`DebugIPC`, `ZeromqIPC`) as they don't have the concept of unsupported signals.

One thing I can do then is create an instance of an "IPC manager" class during `setUp()`.  It's going to be a bit clunky but hopefully you'll like it better :)

2018-05-03 08:02 UTC, gctucker commented
@kov I've reworked this PR and rebased #44 on top of it and added this test case for the `None` signals:
https://github.com/GENIVI/vehicle_signal_manager/pull/44/commits/42ced8cad51c879573a1bd8cd9c899e738c42e13

2018-05-03 10:59 UTC, kov approved these changes
Thanks!

2018-05-03 13:18 UTC, merged